### ISSUE TITLE
Error when startproject: value is not a valid email address (type=value_error.email)

### ISSUE THREAD

**Issue by yourdaddy08** [ycd/manage-fastapi#102]
version==1.1.1
(caas_app) C:\E\proj>fastapi startproject test_fastapi
Traceback (most recent call last):
  File "C:\D\miniconda3\envs\caas_app\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\D\miniconda3\envs\caas_app\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\D\miniconda3\envs\caas_app\Scripts\fastapi.exe\__main__.py", line 7, in <module>
  File "C:\D\miniconda3\envs\caas_app\lib\site-packages\typer\main.py", line 214, in __call__
    return get_command(self)(*args, **kwargs)
  File "C:\D\miniconda3\envs\caas_app\lib\site-packages\click\core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "C:\D\miniconda3\envs\caas_app\lib\site-packages\click\core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "C:\D\miniconda3\envs\caas_app\lib\site-packages\click\core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\D\miniconda3\envs\caas_app\lib\site-packages\click\core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\D\miniconda3\envs\caas_app\lib\site-packages\click\core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "C:\D\miniconda3\envs\caas_app\lib\site-packages\typer\main.py", line 532, in wrapper
    return callback(**use_params)  # type: ignore
  File "C:\D\miniconda3\envs\caas_app\lib\site-packages\manage_fastapi\main.py", line 43, in startproject
    context = ProjectContext(
  File "pydantic\main.py", line 342, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for ProjectContext
email
  value is not a valid email address (type=value_error.email)

**Comment by yuyangncg** [comment]
The reason is that the email format configured on Git is incorrect. You can use the ` git config -- get user. email` command to check and use `git config -- global user. email "youemail@gmail.com"` Configuration.
